#!/usr/bin/env bash
set -ex
HERE=$(dirname $0)
. $HERE/common

docker run -d --rm \
    --pull=always \
    -p 5000:5000 \
    -v ./data:/data \
    -e GROUT_ERROR_TEST=true \
    --name=$PACKAGE_NAME \
    $TAG_SHA